### ISSUE TITLE
Can’t connect to server

### ISSUE THREAD

**Issue by IPlayForHer** [curvehashcoin/CurvehashCoin#1]
Always show me unknown

**Comment by cryptodigi** [comment]
Add nodes from explorer

Il dom 20 dic 2020, 00:47 YouTiao <notifications@github.com> ha scritto:

**Comment by IPlayForHer** [comment]
![image](https://user-images.githubusercontent.com/21272351/102707697-4bba8a80-42f1-11eb-98a8-8330d34ec04b.png)
any nodes address?

**Comment by curvehashcoin** [comment]
http://explorer.curvehash.com/network
